//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServicesWEB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTS
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string BRAND { get; set; }
        public Nullable<decimal> BUYINGPRICE { get; set; }
        public Nullable<decimal> SELLINGPRICE { get; set; }
        public Nullable<short> STOCK { get; set; }
        public Nullable<byte> CATEGORIES { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
