//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServicesWEB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRODUCTFOLLOWING
    {
        public int FOLLOWINGID { get; set; }
        public string EXPLANATION { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string SERIALNO { get; set; }
    }
}
