//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TecnicalServicesWEB.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ABOUTUS
    {
        public byte ID { get; set; }
        public string ABOUTUS { get; set; }
    }
}
